name: testing the node js application
on:
  push: 
    branches:
      - main
jobs:
  test:
    runs-on: node:latest
    steps:
      - name: test-app
        run: npm install
  build:
    runs-on: node:latest
    steps:
      - name: build-app
        run: docker build .
      
